server:
  port: 8081

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://user-mongo:27017/userdb}
  jackson:
    default-property-inclusion: non_null
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: ${JWT_SECRET:changeit-changeit-changeit-changeit-changeit}
    access-token-ttl-seconds: ${ACCESS_TOKEN_TTL:900}
    refresh-token-ttl-seconds: ${REFRESH_TOKEN_TTL:604800}

media:
  service:
    base-url: ${MEDIA_SERVICE_URL:http://media-service:8083}
    enabled: true
    internal-secret: ${MEDIA_INTERNAL_SECRET:internal-change-me}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.buy01.userservice: INFO

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
media:
  service:
    enabled: false
