version: '3.9'

services:
  discovery-service:
    build:
      context: ..
      dockerfile: backend/discovery-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8761:8761'
    networks:
      - buy01-net

  api-gateway:
    build:
      context: ..
      dockerfile: backend/api-gateway/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_DEFAULT_ZONE=http://discovery-service:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - discovery-service
    ports:
      - '8080:8080'
    networks:
      - buy01-net

  user-mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=userdb
    volumes:
      - user-mongo-data:/data/db
    networks:
      - buy01-net

  product-mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=productdb
    volumes:
      - product-mongo-data:/data/db
    networks:
      - buy01-net

  media-mongo:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=mediadb
    volumes:
      - media-mongo-data:/data/db
    networks:
      - buy01-net

  user-service:
    build:
      context: ..
      dockerfile: backend/user-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://user-mongo:27017/userdb
      - EUREKA_DEFAULT_ZONE=http://discovery-service:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - JWT_SECRET=${JWT_SECRET}
      - MEDIA_SERVICE_URL=http://media-service:8083
      - MEDIA_INTERNAL_SECRET=${MEDIA_INTERNAL_SECRET}
      - ACCESS_TOKEN_TTL=900
      - REFRESH_TOKEN_TTL=604800
    depends_on:
      - discovery-service
      - user-mongo
      - media-service
    networks:
      - buy01-net

  product-service:
    build:
      context: ..
      dockerfile: backend/product-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://product-mongo:27017/productdb
      - EUREKA_DEFAULT_ZONE=http://discovery-service:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - JWT_SECRET=${JWT_SECRET}
      - MEDIA_SERVICE_URL=http://media-service:8083
      - MEDIA_INTERNAL_SECRET=${MEDIA_INTERNAL_SECRET}
    depends_on:
      - discovery-service
      - product-mongo
      - media-service
    networks:
      - buy01-net

  media-service:
    build:
      context: ..
      dockerfile: backend/media-service/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGODB_URI=mongodb://media-mongo:27017/mediadb
      - EUREKA_DEFAULT_ZONE=http://discovery-service:8761/eureka
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - JWT_SECRET=${JWT_SECRET}
      - MEDIA_STORAGE_PATH=/app/media-storage
      - MEDIA_SIGNING_SECRET=${MEDIA_SIGNING_SECRET}
      - MEDIA_INTERNAL_SECRET=${MEDIA_INTERNAL_SECRET}
    volumes:
      - media-storage:/app/media-storage
    depends_on:
      - discovery-service
      - media-mongo
    networks:
      - buy01-net

  webapp:
    build:
      context: ..
      dockerfile: frontend/webapp/Dockerfile
    environment:
      - NODE_ENV=production
    depends_on:
      - api-gateway
    ports:
      - '4200:80'
    networks:
      - buy01-net

volumes:
  user-mongo-data:
  product-mongo-data:
  media-mongo-data:
  media-storage:

networks:
  buy01-net:
    driver: bridge
