server:
  port: 8761

spring:
  application:
    name: discovery-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.buy01.discoveryservice: INFO

# Secure access to Eureka with basic auth if needed via env vars
