server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/userdb
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

app:
  jwt:
    secret: change-me-in-env
    expiration: 3600000
